services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/rag_dev
      - EMBED_API_URL=http://embedder:8000/embed
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_EMBED_MODEL=nomic-embed-text   # 768次元
      - OLLAMA_GEN_MODEL=gemma2:2b # より軽量で高速なモデル
      - VECTOR_DIM=768
    volumes:
      - .:/app
    depends_on:
      - db
      - ollama
      - embedder

  db:
    image: pgvector/pgvector:pg16   # pgvector入りのPostgres 16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rag_dev
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rag_dev"]
      interval: 5s
      timeout: 5s
      retries: 20

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  embedder:
    build: ./embedder
    ports:
      - "8000:8000"
    volumes:
      - ./embedder:/app

volumes:
  ollama: {}
  db-data: {}
